### ISSUE TITLE
Empty boxes rendered in Download links

### ISSUE THREAD

**Issue by ashmaroli** [oneclick/rubyinstaller.org-website#6]
The "boxes" do not have a tooltip either.. so the intent is not discernible visually nor by hovering on the link nor by checking the source-code..

![rubyinstaller org_downloads](https://user-images.githubusercontent.com/12479464/34550241-30b7a92c-f135-11e7-9164-53e2ad9ddb78.png)

**Comment by larskanis** [comment]
Thank you for raising this issue! The boxes should really be arrows and they should open additional information to PGP signature and SHA256 hash, when clicked.

I'm not a web designer - it would be a great help, if you could help with a better way to show above information!

**Comment by ashmaroli** [comment]
Well, the links do expand n contract like an accordion-menu when the boxes are clicked.. so it works as expected.., just that the graphic is missing..
no probs.., will submit a PR to resolve this.
