### ISSUE TITLE
rubyinstaller2.org is redirecting to rubyinstaller.org

### ISSUE THREAD

**Issue by luislavena** [oneclick/rubyinstaller.org-website#8]
FYI, bought rubyinstaller2.org domain and setup to permanently redirect to existing domain. That is done as page rules in Cloudflare.

Thought was worth mentioning in case seeing some weird referrals in the analytics.

Cheers.

PS: @larskanis, thank you for your hard work maintaining RubyInstaller2 ❤️ ❤️ ❤️

**Comment by luislavena** [comment]
@larskanis I think adding the donation option is great idea, specially considering you're not only doing maintenance to RubyInstaller, but sending patches to all other dependencies, gems and projects to ensure they work with Windows.

> However this doesn't feel right, since the only real costs (the domain name) for RubyInstaller are still paid by you.

Let me stop you right there. What takes me 10 minutes and a couple of dollars each year is not even close to the amount of work you have invested on this project (and all related) since I left.

So please, do not underestimate your work and contributions, as you are giving things more valuable: your **time** and **knowledge**.

If you go ahead with Patreon or BountySource, you can count with my small contribution 😄 

Once again, thank you for caring and your hard work on RubyInstaller2 ❤️ ❤️ ❤️

**Comment by larskanis** [comment]
Alright, thank you so much! Should I ever come to Argentina I'll try to make a stop in Tucuman to meet you in person and to drink a (German) beer with you!
