### ISSUE TITLE
Recommend a version to use?

### ISSUE THREAD

**Issue by MSP-Greg** [oneclick/rubyinstaller.org-website#9]
Noticed that the home page doesn't really recommend a version to install.

Assuming that:

1. Most extension gems are now testing with 2.5 (and many with trunk).
2. For the first time, most of 2.5 was in development with full testing (test-all & test-spec) on 64 bit builds.  Not the case with 2.4.

Might it be helpful for users to know that the recommendation is to use 2.5.x-x64 unless one has a particular need?  I'm not that familiar with the layout or Jekyll, but I'd be happy to try...

Greg

**Comment by larskanis** [comment]
> Noticed that the home page doesn't really recommend a version to install.

Ruby-2.4.4 with Devkit is what's recommended currently. Isn't it visible enough?

sqlite3 is one binary gem, which isn't yet compatible with ruby-2.5. And it's the default for a new rails app. I would like to wait some more months until changing the recommendation.

**Comment by MSP-Greg** [comment]
> Isn't it visible enough?

Probably not the person to ask.  I've always felt that if what people (believe they) want is on the home page, they'll never go further (the download links).

> sqlite3 is one binary gem, which isn't yet compatible with ruby-2.5. And it's the default for a new rails app

And Rails (and its dependencies) is the criteria...

Thanks, Greg

**Comment by MSP-Greg** [comment]
Re sqlite3, using my 'do it on Appveyor' fat-binary gem building system, I've got sqlite3 64 bit building & testing with Ruby 2.0 thru 2.5, and 32 bit building/testing with 2.4 & 2.5.  Also, that's with the newest version of SQLite3, 3.24.0.  The current fat-binaries use 3.8.11.1.

It seems that there is not much interest in building fat-binary gems on Appveyor, and with that goes a delay in adding 2.4 and/or 2.5 to them.

Funny, in Ruby Core, if I could describe/repo a Windows issue, they fixed it.  For all the complaining I've seen in the past about the 'Ruby Core group', they certainly seem more supportive of Windows than many gem maintainers...

Sorry for the brief rant.  You didn't need to write the RI2 runtime for yourself, you wrote it for others (thanks again).  As a reasonably competent 'builder' and user of trunk, I don't need (or can't use) fat-binary gems.  But others do...

Thanks, Greg

**Comment by larskanis** [comment]
There's a clear recommendation of the [download page](https://rubyinstaller.org/downloads/) now, so I'm closing this. Thanks @MSP-Greg !
